const e000 = document.getElementById('e000')
const e001 = document.getElementById('e001')
const e002 = document.getElementById('e002')
const e003 = document.getElementById('e003')
const e004 = document.getElementById('e004')
const e010 = document.getElementById('e010')
const e011 = document.getElementById('e011')
const e012 = document.getElementById('e012')
const e013 = document.getElementById('e013')
const e014 = document.getElementById('e014')
const e020 = document.getElementById('e020')
const e021 = document.getElementById('e021')
const e022 = document.getElementById('e022')
const e023 = document.getElementById('e023')
const e024 = document.getElementById('e024')
const e030 = document.getElementById('e030')
const e031 = document.getElementById('e031')
const e032 = document.getElementById('e032')
const e033 = document.getElementById('e033')
const e034 = document.getElementById('e034')
const e040 = document.getElementById('e040')
const e041 = document.getElementById('e041')
const e042 = document.getElementById('e042')
const e043 = document.getElementById('e043')
const e044 = document.getElementById('e044')
const e050 = document.getElementById('e050')
const e051 = document.getElementById('e051')
const e052 = document.getElementById('e052')
const e053 = document.getElementById('e053')
const e054 = document.getElementById('e054')
const e060 = document.getElementById('e060')
const e061 = document.getElementById('e061')
const e062 = document.getElementById('e062')
const e063 = document.getElementById('e063')
const e064 = document.getElementById('e064')

const e100 = document.getElementById('e100')
const e101 = document.getElementById('e101')
const e102 = document.getElementById('e102')
const e103 = document.getElementById('e103')
const e104 = document.getElementById('e104')
const e110 = document.getElementById('e110')
const e111 = document.getElementById('e111')
const e112 = document.getElementById('e112')
const e113 = document.getElementById('e113')
const e114 = document.getElementById('e114')
const e120 = document.getElementById('e120')
const e121 = document.getElementById('e121')
const e122 = document.getElementById('e122')
const e123 = document.getElementById('e123')
const e124 = document.getElementById('e124')
const e130 = document.getElementById('e130')
const e131 = document.getElementById('e131')
const e132 = document.getElementById('e132')
const e133 = document.getElementById('e133')
const e134 = document.getElementById('e134')
const e140 = document.getElementById('e140')
const e141 = document.getElementById('e141')
const e142 = document.getElementById('e142')
const e143 = document.getElementById('e143')
const e144 = document.getElementById('e144')
const e150 = document.getElementById('e150')
const e151 = document.getElementById('e151')
const e152 = document.getElementById('e152')
const e153 = document.getElementById('e153')
const e154 = document.getElementById('e154')
const e160 = document.getElementById('e160')
const e161 = document.getElementById('e161')
const e162 = document.getElementById('e162')
const e163 = document.getElementById('e163')
const e164 = document.getElementById('e164')

const e200 = document.getElementById('e200')
const e201 = document.getElementById('e201')
const e202 = document.getElementById('e202')
const e203 = document.getElementById('e203')
const e204 = document.getElementById('e204')
const e210 = document.getElementById('e210')
const e211 = document.getElementById('e211')
const e212 = document.getElementById('e212')
const e213 = document.getElementById('e213')
const e214 = document.getElementById('e214')
const e220 = document.getElementById('e220')
const e221 = document.getElementById('e221')
const e222 = document.getElementById('e222')
const e223 = document.getElementById('e223')
const e224 = document.getElementById('e224')
const e230 = document.getElementById('e230')
const e231 = document.getElementById('e231')
const e232 = document.getElementById('e232')
const e233 = document.getElementById('e233')
const e234 = document.getElementById('e234')
const e240 = document.getElementById('e240')
const e241 = document.getElementById('e241')
const e242 = document.getElementById('e242')
const e243 = document.getElementById('e243')
const e244 = document.getElementById('e244')
const e250 = document.getElementById('e250')
const e251 = document.getElementById('e251')
const e252 = document.getElementById('e252')
const e253 = document.getElementById('e253')
const e254 = document.getElementById('e254')
const e260 = document.getElementById('e260')
const e261 = document.getElementById('e261')
const e262 = document.getElementById('e262')
const e263 = document.getElementById('e263')
const e264 = document.getElementById('e264')

const e300 = document.getElementById('e300')
const e301 = document.getElementById('e301')
const e302 = document.getElementById('e302')
const e303 = document.getElementById('e303')
const e304 = document.getElementById('e304')
const e310 = document.getElementById('e310')
const e311 = document.getElementById('e311')
const e312 = document.getElementById('e312')
const e313 = document.getElementById('e313')
const e314 = document.getElementById('e314')
const e320 = document.getElementById('e320')
const e321 = document.getElementById('e321')
const e322 = document.getElementById('e322')
const e323 = document.getElementById('e323')
const e324 = document.getElementById('e324')
const e330 = document.getElementById('e330')
const e331 = document.getElementById('e331')
const e332 = document.getElementById('e332')
const e333 = document.getElementById('e333')
const e334 = document.getElementById('e334')
const e340 = document.getElementById('e340')
const e341 = document.getElementById('e341')
const e342 = document.getElementById('e342')
const e343 = document.getElementById('e343')
const e344 = document.getElementById('e344')
const e350 = document.getElementById('e350')
const e351 = document.getElementById('e351')
const e352 = document.getElementById('e352')
const e353 = document.getElementById('e353')
const e354 = document.getElementById('e354')
const e360 = document.getElementById('e360')
const e361 = document.getElementById('e361')
const e362 = document.getElementById('e362')
const e363 = document.getElementById('e363')
const e364 = document.getElementById('e364')

const e400 = document.getElementById('e400')
const e401 = document.getElementById('e401')
const e402 = document.getElementById('e402')
const e403 = document.getElementById('e403')
const e404 = document.getElementById('e404')
const e410 = document.getElementById('e410')
const e411 = document.getElementById('e411')
const e412 = document.getElementById('e412')
const e413 = document.getElementById('e413')
const e414 = document.getElementById('e414')
const e420 = document.getElementById('e420')
const e421 = document.getElementById('e421')
const e422 = document.getElementById('e422')
const e423 = document.getElementById('e423')
const e424 = document.getElementById('e424')
const e430 = document.getElementById('e430')
const e431 = document.getElementById('e431')
const e432 = document.getElementById('e432')
const e433 = document.getElementById('e433')
const e434 = document.getElementById('e434')
const e440 = document.getElementById('e440')
const e441 = document.getElementById('e441')
const e442 = document.getElementById('e442')
const e443 = document.getElementById('e443')
const e444 = document.getElementById('e444')
const e450 = document.getElementById('e450')
const e451 = document.getElementById('e451')
const e452 = document.getElementById('e452')
const e453 = document.getElementById('e453')
const e454 = document.getElementById('e454')
const e460 = document.getElementById('e460')
const e461 = document.getElementById('e461')
const e462 = document.getElementById('e462')
const e463 = document.getElementById('e463')
const e464 = document.getElementById('e464')

const e500 = document.getElementById('e500')
const e501 = document.getElementById('e501')
const e502 = document.getElementById('e502')
const e503 = document.getElementById('e503')
const e504 = document.getElementById('e504')
const e510 = document.getElementById('e510')
const e511 = document.getElementById('e511')
const e512 = document.getElementById('e512')
const e513 = document.getElementById('e513')
const e514 = document.getElementById('e514')
const e520 = document.getElementById('e520')
const e521 = document.getElementById('e521')
const e522 = document.getElementById('e522')
const e523 = document.getElementById('e523')
const e524 = document.getElementById('e524')
const e530 = document.getElementById('e530')
const e531 = document.getElementById('e531')
const e532 = document.getElementById('e532')
const e533 = document.getElementById('e533')
const e534 = document.getElementById('e534')
const e540 = document.getElementById('e540')
const e541 = document.getElementById('e541')
const e542 = document.getElementById('e542')
const e543 = document.getElementById('e543')
const e544 = document.getElementById('e544')
const e550 = document.getElementById('e550')
const e551 = document.getElementById('e551')
const e552 = document.getElementById('e552')
const e553 = document.getElementById('e553')
const e554 = document.getElementById('e554')
const e560 = document.getElementById('e560')
const e561 = document.getElementById('e561')
const e562 = document.getElementById('e562')
const e563 = document.getElementById('e563')
const e564 = document.getElementById('e564')

const e600 = document.getElementById('e600')
const e601 = document.getElementById('e601')
const e602 = document.getElementById('e602')
const e603 = document.getElementById('e603')
const e604 = document.getElementById('e604')
const e610 = document.getElementById('e610')
const e611 = document.getElementById('e611')
const e612 = document.getElementById('e612')
const e613 = document.getElementById('e613')
const e614 = document.getElementById('e614')
const e620 = document.getElementById('e620')
const e621 = document.getElementById('e621')
const e622 = document.getElementById('e622')
const e623 = document.getElementById('e623')
const e624 = document.getElementById('e624')
const e630 = document.getElementById('e630')
const e631 = document.getElementById('e631')
const e632 = document.getElementById('e632')
const e633 = document.getElementById('e633')
const e634 = document.getElementById('e634')
const e640 = document.getElementById('e640')
const e641 = document.getElementById('e641')
const e642 = document.getElementById('e642')
const e643 = document.getElementById('e643')
const e644 = document.getElementById('e644')
const e650 = document.getElementById('e650')
const e651 = document.getElementById('e651')
const e652 = document.getElementById('e652')
const e653 = document.getElementById('e653')
const e654 = document.getElementById('e654')
const e660 = document.getElementById('e660')
const e661 = document.getElementById('e661')
const e662 = document.getElementById('e662')
const e663 = document.getElementById('e663')
const e664 = document.getElementById('e664')

const e700 = document.getElementById('e700')
const e701 = document.getElementById('e701')
const e702 = document.getElementById('e702')
const e703 = document.getElementById('e703')
const e704 = document.getElementById('e704')
const e710 = document.getElementById('e710')
const e711 = document.getElementById('e711')
const e712 = document.getElementById('e712')
const e713 = document.getElementById('e713')
const e714 = document.getElementById('e714')
const e720 = document.getElementById('e720')
const e721 = document.getElementById('e721')
const e722 = document.getElementById('e722')
const e723 = document.getElementById('e723')
const e724 = document.getElementById('e724')
const e730 = document.getElementById('e730')
const e731 = document.getElementById('e731')
const e732 = document.getElementById('e732')
const e733 = document.getElementById('e733')
const e734 = document.getElementById('e734')
const e740 = document.getElementById('e740')
const e741 = document.getElementById('e741')
const e742 = document.getElementById('e742')
const e743 = document.getElementById('e743')
const e744 = document.getElementById('e744')
const e750 = document.getElementById('e750')
const e751 = document.getElementById('e751')
const e752 = document.getElementById('e752')
const e753 = document.getElementById('e753')
const e754 = document.getElementById('e754')
const e760 = document.getElementById('e760')
const e761 = document.getElementById('e761')
const e762 = document.getElementById('e762')
const e763 = document.getElementById('e763')
const e764 = document.getElementById('e764')

const e800 = document.getElementById('e800')
const e801 = document.getElementById('e801')
const e802 = document.getElementById('e802')
const e803 = document.getElementById('e803')
const e804 = document.getElementById('e804')
const e810 = document.getElementById('e810')
const e811 = document.getElementById('e811')
const e812 = document.getElementById('e812')
const e813 = document.getElementById('e813')
const e814 = document.getElementById('e814')
const e820 = document.getElementById('e820')
const e821 = document.getElementById('e821')
const e822 = document.getElementById('e822')
const e823 = document.getElementById('e823')
const e824 = document.getElementById('e824')
const e830 = document.getElementById('e830')
const e831 = document.getElementById('e831')
const e832 = document.getElementById('e832')
const e833 = document.getElementById('e833')
const e834 = document.getElementById('e834')
const e840 = document.getElementById('e840')
const e841 = document.getElementById('e841')
const e842 = document.getElementById('e842')
const e843 = document.getElementById('e843')
const e844 = document.getElementById('e844')
const e850 = document.getElementById('e850')
const e851 = document.getElementById('e851')
const e852 = document.getElementById('e852')
const e853 = document.getElementById('e853')
const e854 = document.getElementById('e854')
const e860 = document.getElementById('e860')
const e861 = document.getElementById('e861')
const e862 = document.getElementById('e862')
const e863 = document.getElementById('e863')
const e864 = document.getElementById('e864')

const e900 = document.getElementById('e900')
const e901 = document.getElementById('e901')
const e902 = document.getElementById('e902')
const e903 = document.getElementById('e903')
const e904 = document.getElementById('e904')
const e910 = document.getElementById('e910')
const e911 = document.getElementById('e911')
const e912 = document.getElementById('e912')
const e913 = document.getElementById('e913')
const e914 = document.getElementById('e914')
const e920 = document.getElementById('e920')
const e921 = document.getElementById('e921')
const e922 = document.getElementById('e922')
const e923 = document.getElementById('e923')
const e924 = document.getElementById('e924')
const e930 = document.getElementById('e930')
const e931 = document.getElementById('e931')
const e932 = document.getElementById('e932')
const e933 = document.getElementById('e933')
const e934 = document.getElementById('e934')
const e940 = document.getElementById('e940')
const e941 = document.getElementById('e941')
const e942 = document.getElementById('e942')
const e943 = document.getElementById('e943')
const e944 = document.getElementById('e944')
const e950 = document.getElementById('e950')
const e951 = document.getElementById('e951')
const e952 = document.getElementById('e952')
const e953 = document.getElementById('e953')
const e954 = document.getElementById('e954')
const e960 = document.getElementById('e960')
const e961 = document.getElementById('e961')
const e962 = document.getElementById('e962')
const e963 = document.getElementById('e963')
const e964 = document.getElementById('e964')

function turnOn(egg, color = '#FFBC03') {
    egg.style.color = color
}

function turnOff(egg) {
    egg.style.color = '#000000'
}

// Make digit 0
turnOff(e000)
turnOn(e001)
turnOn(e002)
turnOn(e003)
turnOff(e004)
turnOn(e010)
turnOff(e011)
turnOff(e012)
turnOff(e013)
turnOn(e014)
turnOn(e020)
turnOff(e021)
turnOff(e022)
turnOff(e023)
turnOn(e024)
turnOn(e030)
turnOff(e031)
turnOff(e032)
turnOff(e033)
turnOn(e034)
turnOn(e040)
turnOff(e041)
turnOff(e042)
turnOff(e043)
turnOn(e044)
turnOn(e050)
turnOff(e051)
turnOff(e052)
turnOff(e053)
turnOn(e054)
turnOff(e060)
turnOn(e061)
turnOn(e062)
turnOn(e063)
turnOff(e064)

// Make digit 1
turnOff(e100)
turnOff(e101)
turnOff(e103)
turnOff(e104)
turnOff(e110)
turnOff(e113)
turnOff(e114)
turnOff(e120)
turnOff(e121)
turnOff(e123)
turnOff(e124)
turnOff(e130)
turnOff(e131)
turnOff(e133)
turnOff(e134)
turnOff(e140)
turnOff(e141)
turnOff(e143)
turnOff(e144)
turnOff(e150)
turnOff(e151)
turnOff(e153)
turnOff(e154)
turnOff(e160)
turnOff(e164)

// Make digit 2
turnOff(e200)
turnOff(e204)
turnOff(e211)
turnOff(e212)
turnOff(e213)
turnOff(e220)
turnOff(e221)
turnOff(e222)
turnOff(e223)
turnOff(e230)
turnOff(e234)
turnOff(e241)
turnOff(e242)
turnOff(e243)
turnOff(e244)
turnOff(e251)
turnOff(e252)
turnOff(e253)
turnOff(e254)

// Make digit 3
turnOff(e300)
turnOff(e304)
turnOff(e311)
turnOff(e312)
turnOff(e313)
turnOff(e320)
turnOff(e321)
turnOff(e322)
turnOff(e323)
turnOff(e330)
turnOff(e334)
turnOff(e340)
turnOff(e341)
turnOff(e342)
turnOff(e343)
turnOff(e351)
turnOff(e352)
turnOff(e353)
turnOff(e360)
turnOff(e364)

// Make digit 4
turnOff(e401)
turnOff(e402)
turnOff(e403)
turnOff(e411)
turnOff(e412)
turnOff(e413)
turnOff(e421)
turnOff(e422)
turnOff(e423)
turnOff(e440)
turnOff(e441)
turnOff(e442)
turnOff(e443)
turnOff(e450)
turnOff(e451)
turnOff(e452)
turnOff(e453)
turnOff(e460)
turnOff(e461)
turnOff(e462)
turnOff(e463)

// Make digit 5
turnOff(e511)
turnOff(e512)
turnOff(e513)
turnOff(e514)
turnOff(e521)
turnOff(e522)
turnOff(e523)
turnOff(e524)
turnOff(e534)
turnOff(e540)
turnOff(e541)
turnOff(e542)
turnOff(e543)
turnOff(e550)
turnOff(e551)
turnOff(e552)
turnOff(e553)
turnOff(e564)

// Make digit 6
turnOff(e600)
turnOff(e604)
turnOff(e611)
turnOff(e612)
turnOff(e613)
turnOff(e614)
turnOff(e621)
turnOff(e622)
turnOff(e623)
turnOff(e624)
turnOff(e634)
turnOff(e641)
turnOff(e642)
turnOff(e643)
turnOff(e651)
turnOff(e652)
turnOff(e653)
turnOff(e660)
turnOff(e664)

// Make digit 7
turnOff(e710)
turnOff(e711)
turnOff(e712)
turnOff(e713)
turnOff(e720)
turnOff(e721)
turnOff(e722)
turnOff(e723)
turnOff(e730)
turnOff(e731)
turnOff(e732)
turnOff(e734)
turnOff(e740)
turnOff(e741)
turnOff(e743)
turnOff(e744)
turnOff(e750)
turnOff(e751)
turnOff(e753)
turnOff(e754)
turnOff(e760)
turnOff(e761)
turnOff(e763)
turnOff(e764)

// Make digit 8
turnOff(e800)
turnOff(e804)
turnOff(e811)
turnOff(e812)
turnOff(e813)
turnOff(e821)
turnOff(e822)
turnOff(e823)
turnOff(e830)
turnOff(e834)
turnOff(e841)
turnOff(e842)
turnOff(e843)
turnOff(e851)
turnOff(e852)
turnOff(e853)
turnOff(e860)
turnOff(e864)

// Make digit 9
turnOff(e900)
turnOff(e904)
turnOff(e911)
turnOff(e912)
turnOff(e913)
turnOff(e921)
turnOff(e922)
turnOff(e923)
turnOff(e930)
turnOff(e940)
turnOff(e941)
turnOff(e942)
turnOff(e943)
turnOff(e950)
turnOff(e951)
turnOff(e952)
turnOff(e953)
turnOff(e960)
turnOff(e964)



const startButton = document.getElementById('start-button')
const stopButton = document.getElementById('stop-button')
const resetButton = document.getElementById('reset-button')

function makeEggcrateContainers(name, numBoxes, boxId = 0){
    const eggHTML = []
    for (let i = 0; i < numBoxes; i++) {

        boxId++

        eggHTML.push(
            `<div class="eggcrate-container" id="${name}${boxId}">
    <div class="eggcrate-row"><span class="egg" id="e${boxId}00">•</span><span class="egg" id="e${boxId}01">•</span><span class="egg" id="e${boxId}02">•</span><span class="egg" id="e${boxId}03">•</span><span class="egg" id="e${boxId}04">•</span></div>
    <div class="eggcrate-row"><span class="egg" id="e${boxId}10">•</span><span class="egg" id="e${boxId}11">•</span><span class="egg" id="e${boxId}12">•</span><span class="egg" id="e${boxId}13">•</span><span class="egg" id="e${boxId}14">•</span></div>
    <div class="eggcrate-row"><span class="egg" id="e${boxId}20">•</span><span class="egg" id="e${boxId}21">•</span><span class="egg" id="e${boxId}22">•</span><span class="egg" id="e${boxId}23">•</span><span class="egg" id="e${boxId}24">•</span></div>
    <div class="eggcrate-row"><span class="egg" id="e${boxId}30">•</span><span class="egg" id="e${boxId}31">•</span><span class="egg" id="e${boxId}32">•</span><span class="egg" id="e${boxId}33">•</span><span class="egg" id="e${boxId}34">•</span></div>
    <div class="eggcrate-row"><span class="egg" id="e${boxId}40">•</span><span class="egg" id="e${boxId}41">•</span><span class="egg" id="e${boxId}42">•</span><span class="egg" id="e${boxId}43">•</span><span class="egg" id="e${boxId}44">•</span></div>
    <div class="eggcrate-row"><span class="egg" id="e${boxId}50">•</span><span class="egg" id="e${boxId}51">•</span><span class="egg" id="e${boxId}52">•</span><span class="egg" id="e${boxId}53">•</span><span class="egg" id="e${boxId}54">•</span></div>
    <div class="eggcrate-row"><span class="egg" id="e${boxId}60">•</span><span class="egg" id="e${boxId}61">•</span><span class="egg" id="e${boxId}62">•</span><span class="egg" id="e${boxId}63">•</span><span class="egg" id="e${boxId}64">•</span></div>
    </div>`
        )
    }
    return eggHTML
}

function startTimer(time) {
    const timerContainer = document.getElementById('timer-container')
    timerContainer.style.display = 'inline-flex'
    let numDigits = 0
    if (time < 10) {
        numDigits = 1
    } else if (time < 100) {
        numDigits = 2
    } else if (time < 1000) {
        numDigits = 3
    }
    const timeDigits = []
    setTimeDigits(timeDigits, time)
    const timerHTML = makeEggcrateContainers('time',3, 9)



    timerContainer.innerHTML = timerHTML.join('')
    if(time < 100){
        timerContainer.children[0].style.display = 'none'
    }
    if(time < 10){
        timerContainer.children[1].style.display = 'none'
    }

    const timerMessage = document.getElementById('timer-message')
    timerMessage.style.color = '#333333'
    light(timerContainer.children[0], timeDigits[0])
    light(timerContainer.children[1], timeDigits[1])
    light(timerContainer.children[2], timeDigits[2])
    const interval = setInterval(() => {
        stopButton.addEventListener('click', (e) => {
            e.preventDefault()
            clearInterval(interval)
            timerContainer.style.display = 'inline-flex'
            document.getElementById('timeInput').value = time
        })

        function resetTimer() {
            clearInterval(interval)
            time = 0
            timerContainer.style.display = 'none'
            timerMessage.textContent = ''
        }

        resetButton.addEventListener('click', (e) => {
            e.preventDefault()
            resetTimer()
        })
        let color = '#FFBC03'
        if (time > 0) {
            time -= 1
            if(time <= 10){
                color = '#FF0000'
                timerContainer.children[0].style.boxShadow = '0 0 5px #FF0000'
                timerContainer.children[1].style.boxShadow = '0 0 5px #FF0000'
                timerContainer.children[2].style.boxShadow = '0 0 5px #FF0000'
            }
            if(time < 100){
                timerContainer.children[0].style.display = 'none'
            }
            if(time < 10){
                timerContainer.children[1].style.display = 'none'
            }
            timerMessage.textContent = time
            setTimeDigits(timeDigits, time)
            console.log(time)
            light(timerContainer.children[0], timeDigits[0], color)
            light(timerContainer.children[1], timeDigits[1], color)
            light(timerContainer.children[2], timeDigits[2], color)
        } else {
            clearInterval(interval)
            clearInterval(interval)
            timerMessage.textContent = 'TIME UP'
            timerMessage.style.color = '#FF0000'
            timerContainer.children[0].style.boxShadow = '0 0 5px #FF0000'
            timerContainer.children[1].style.boxShadow = '0 0 5px #FF0000'
            timerContainer.children[2].style.boxShadow = '0 0 5px #FF0000'
            for (let i = 0; i < 3; i++) {
                light(timerContainer.children[i], 0, '#FF0000')
            }

        }
    }, 1000)
}

startButton.addEventListener('click', (e) => {
    e.preventDefault()
    const time = parseInt(document.getElementById('timeInput').value)
    startTimer(time)
})


function light0(box, color = '#FFBC03'){
    turnOff(box.children[0].children[0], color)
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOff(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOn(box.children[1].children[4], color)
    turnOn(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOn(box.children[2].children[4], color)
    turnOn(box.children[3].children[0], color)
    turnOff(box.children[3].children[1], color)
    turnOff(box.children[3].children[2], color)
    turnOff(box.children[3].children[3], color)
    turnOn(box.children[3].children[4], color)
    turnOn(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOn(box.children[4].children[4], color)
    turnOn(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOn(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light1(box, color = '#FFBC03'){
    turnOff(box.children[0].children[0], color)
    turnOff(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOff(box.children[0].children[3], color)
    turnOff(box.children[0].children[4], color)
    turnOff(box.children[1].children[0], color)
    turnOn(box.children[1].children[1], color)
    turnOn(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOff(box.children[1].children[4], color)
    turnOff(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOn(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOff(box.children[2].children[4], color)
    turnOff(box.children[3].children[0], color)
    turnOff(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOff(box.children[3].children[3], color)
    turnOff(box.children[3].children[4], color)
    turnOff(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOn(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOff(box.children[4].children[4], color)
    turnOff(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOn(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOff(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light2(box, color = '#FFBC03'){
    turnOff(box.children[0].children[0])
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOff(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOn(box.children[1].children[4], color)
    turnOff(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOn(box.children[2].children[4], color)
    turnOff(box.children[3].children[0], color)
    turnOn(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOff(box.children[3].children[4], color)
    turnOn(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOff(box.children[4].children[4], color)
    turnOn(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOff(box.children[5].children[4], color)
    turnOn(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOn(box.children[6].children[4], color)
}
function light3(box, color = '#FFBC03'){
    turnOff(box.children[0].children[0], color)
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOff(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOn(box.children[1].children[4], color)
    turnOff(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOn(box.children[2].children[4], color)
    turnOff(box.children[3].children[0], color)
    turnOn(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOff(box.children[3].children[4], color)
    turnOff(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOn(box.children[4].children[4], color)
    turnOn(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOn(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light4(box, color = '#FFBC03'){
    turnOn(box.children[0].children[0], color)
    turnOff(box.children[0].children[1], color)
    turnOff(box.children[0].children[2], color)
    turnOff(box.children[0].children[3], color)
    turnOn(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOn(box.children[1].children[4], color)
    turnOn(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOn(box.children[2].children[4], color)
    turnOn(box.children[3].children[0], color)
    turnOn(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOn(box.children[3].children[4], color)
    turnOff(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOn(box.children[4].children[4], color)
    turnOff(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOn(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOff(box.children[6].children[1], color)
    turnOff(box.children[6].children[2], color)
    turnOff(box.children[6].children[3], color)
    turnOn(box.children[6].children[4], color)
}
function light5(box, color = '#FFBC03'){
    turnOn(box.children[0].children[0], color)
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOn(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOff(box.children[1].children[4], color)
    turnOn(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOff(box.children[2].children[4], color)
    turnOn(box.children[3].children[0], color)
    turnOn(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOff(box.children[3].children[4], color)
    turnOff(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOn(box.children[4].children[4], color)
    turnOff(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOn(box.children[5].children[4], color)
    turnOn(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light6(box, color = '#FFBC03'){
    turnOff(box.children[0].children[0], color)
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOff(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOff(box.children[1].children[4], color)
    turnOn(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOff(box.children[2].children[4], color)
    turnOn(box.children[3].children[0], color)
    turnOn(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOff(box.children[3].children[4], color)
    turnOn(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOn(box.children[4].children[4], color)
    turnOn(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOn(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light7(box, color = '#FFBC03'){
    turnOn(box.children[0].children[0], color)
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOn(box.children[0].children[4], color)
    turnOff(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOn(box.children[1].children[4], color)
    turnOff(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOn(box.children[2].children[4], color)
    turnOff(box.children[3].children[0], color)
    turnOff(box.children[3].children[1], color)
    turnOff(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOff(box.children[3].children[4], color)
    turnOff(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOn(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOff(box.children[4].children[4], color)
    turnOff(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOn(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOff(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOff(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOff(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light8(box, color = '#FFBC03'){
    turnOff(box.children[0].children[0], color)
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOff(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOn(box.children[1].children[4], color)
    turnOn(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOn(box.children[2].children[4], color)
    turnOff(box.children[3].children[0], color)
    turnOn(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOff(box.children[3].children[4], color)
    turnOn(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOn(box.children[4].children[4], color)
    turnOn(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOn(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light9(box, color = '#FFBC03'){
    turnOff(box.children[0].children[0], color)
    turnOn(box.children[0].children[1], color)
    turnOn(box.children[0].children[2], color)
    turnOn(box.children[0].children[3], color)
    turnOff(box.children[0].children[4], color)
    turnOn(box.children[1].children[0], color)
    turnOff(box.children[1].children[1], color)
    turnOff(box.children[1].children[2], color)
    turnOff(box.children[1].children[3], color)
    turnOn(box.children[1].children[4], color)
    turnOn(box.children[2].children[0], color)
    turnOff(box.children[2].children[1], color)
    turnOff(box.children[2].children[2], color)
    turnOff(box.children[2].children[3], color)
    turnOn(box.children[2].children[4], color)
    turnOff(box.children[3].children[0], color)
    turnOn(box.children[3].children[1], color)
    turnOn(box.children[3].children[2], color)
    turnOn(box.children[3].children[3], color)
    turnOn(box.children[3].children[4], color)
    turnOff(box.children[4].children[0], color)
    turnOff(box.children[4].children[1], color)
    turnOff(box.children[4].children[2], color)
    turnOff(box.children[4].children[3], color)
    turnOn(box.children[4].children[4], color)
    turnOff(box.children[5].children[0], color)
    turnOff(box.children[5].children[1], color)
    turnOff(box.children[5].children[2], color)
    turnOff(box.children[5].children[3], color)
    turnOn(box.children[5].children[4], color)
    turnOff(box.children[6].children[0], color)
    turnOn(box.children[6].children[1], color)
    turnOn(box.children[6].children[2], color)
    turnOn(box.children[6].children[3], color)
    turnOff(box.children[6].children[4], color)
}
function light(box, int, color = '#FFBC03'){
    switch(int){
        case 0: light0(box, color); break;
        case 1: light1(box, color); break;
        case 2: light2(box, color); break;
        case 3: light3(box, color); break;
        case 4: light4(box, color); break;
        case 5: light5(box, color); break;
        case 6: light6(box, color); break;
        case 7: light7(box, color); break;
        case 8: light8(box, color); break;
        case 9: light9(box, color); break;
        default: throw new RangeError(`${int} cannot be lit`);
    }
}
function setTimeDigits(arr, int){
    arr[0] = Math.floor((int % 1000) / 100)
    arr[1] = Math.floor((int % 100) / 10);
    arr[2] = Math.floor(int % 10);

}